name: CI/CD Pipeline by Fortress Technologies Inc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # Run on your local agent runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"   # LTS

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"   # Latest LTS
          cache: "npm"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq build-essential

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build microservice images locally
        run: |
          services=(
            adservice
            cartservice/src
            checkoutservice
            currencyservice
            emailservice
            frontend
            loadgenerator
            paymentservice
            productcatalogservice
            recommendationservice
            shippingservice
          )
          for svc in "${services[@]}"; do
            name=$(basename "$svc")
            echo "⚙️ Building $name locally..."
            docker build \
              -t iscanprint/$name:1 \
              src/$svc
          done
